name: CI

on:
  # Only run push on main
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  # Always run on PRs
  pull_request:
  merge_group:

concurrency:
  group: '${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew check

      - name: (Fail-only) Upload build reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: |
            **/build/reports/*

  publish-snapshots:
    name: "Publish snapshots"
    if: github.repository == 'slackhq/compose-lints' && github.ref == 'refs/heads/main'
    needs: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Publish
        run: ./gradlew publish -PmavenCentralUsername=${{ secrets.SONATYPEUSERNAME }} -PmavenCentralPassword=${{ secrets.SONATYPEPASSWORD }} --no-configuration-cache
